import type { Metadata } from "next";
/* eslint-disable @next/next/no-html-link-for-pages */

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How PriceWatch handles account and product-monitoring data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return <main className="legal-page"><header><a href="/" className="legal-logo"><span>ϟ</span>PriceWatch</a><a href="/login">Sign in</a></header><article><span className="section-label">LAST UPDATED · 22 AUGUST 2026</span><h1>Privacy Policy</h1><p className="legal-lead">PriceWatch is designed to collect the minimum information needed to operate a competitor-monitoring workspace.</p><section><h2>Information we process</h2><p>We process account identity information supplied by the sign-in provider, including your name and email address. When you use the product, we also process the product names, SKUs, public competitor URLs, alert preferences, and monitoring configuration that you provide.</p></section><section><h2>Public-page observations</h2><p>PriceWatch may record product names, displayed prices, currencies, stock availability, timestamps, and related public business information from supported product pages. The service is not intended to collect personal information from target websites.</p></section><section><h2>How information is used</h2><p>Information is used to provide monitoring, price history, alerts, account support, reliability, security, and product improvement. We do not sell account information or use monitored product data for unrelated advertising.</p></section><section><h2>Retention and control</h2><p>Monitoring records are retained while needed to provide price history and the service. Users should be able to remove tracked URLs and close their workspace. Operational records may be retained for a limited period for security, troubleshooting, and legal compliance.</p></section><section><h2>Service providers</h2><p>PriceWatch may rely on hosting, authentication, email, analytics, and payment providers. Those providers process information only as needed to deliver their respective services and under their own applicable terms.</p></section><section><h2>Your responsibilities</h2><p>Only submit public product URLs you are permitted to monitor. Do not submit login credentials, private pages, personal profiles, or sensitive personal information.</p></section><section><h2>Policy changes</h2><p>Material changes will be reflected by updating the date at the top of this page. Additional operator and contact details must be added before a public commercial launch.</p></section></article><footer><a href="/terms">Terms</a><a href="/">Back to PriceWatch</a></footer></main>;
}
