import type { Metadata } from "next";
/* eslint-disable @next/next/no-html-link-for-pages */

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "Terms for using the Nexus early-access service.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return <main className="legal-page"><header><a href="/" className="legal-logo"><span>ϟ</span>Nexus</a><a href="/login">Sign in</a></header><article><span className="section-label">EARLY ACCESS · 22 AUGUST 2026</span><h1>Terms of Use</h1><p className="legal-lead">These terms describe the intended use of the Nexus early-access product. Operator details and jurisdiction-specific terms must be completed before a public paid launch.</p><section><h2>The service</h2><p>Nexus helps users monitor price and availability information displayed on supported public product pages. Monitoring frequency, supported stores, extraction accuracy, and availability may vary during early access.</p></section><section><h2>Acceptable use</h2><p>You may use Nexus only for lawful business purposes and public information you are permitted to monitor. You must not use the service to bypass logins, CAPTCHAs, paywalls, access controls, or website restrictions; collect sensitive personal information; overload target websites; or violate applicable law or contractual obligations.</p></section><section><h2>Your account</h2><p>You are responsible for activity performed through your account, for keeping access secure, and for the accuracy and legality of URLs and product information submitted to the service.</p></section><section><h2>Early-access limitations</h2><p>The product may change, contain errors, or experience interruptions. Example dashboard records are clearly presented as demonstration data and should not be relied on for purchasing, pricing, or financial decisions.</p></section><section><h2>Pricing and billing</h2><p>Prices displayed on the marketing site are proposed early-access plans. Billing is not active unless a separate checkout and subscription agreement is presented and accepted.</p></section><section><h2>Third-party websites</h2><p>Target websites remain controlled by their respective owners. Nexus does not endorse them and cannot guarantee that their content, layout, access rules, or availability will remain unchanged.</p></section><section><h2>Warranty and liability</h2><p>The early-access service is provided on an as-available basis. To the extent permitted by law, Nexus disclaims implied warranties and is not liable for decisions made solely from incomplete, delayed, or incorrect observations.</p></section><section><h2>Launch completion</h2><p>Before accepting public paid customers, these terms must be reviewed and completed with the operator’s legal name, address, contact information, governing law, cancellation rules, and any mandatory consumer or business disclosures.</p></section></article><footer><a href="/privacy">Privacy</a><a href="/">Back to Nexus</a></footer></main>;
}
